# Specify a command to be executed
# like `/bin/bash -l`, `ls`, or any other commands
# the default is bash for Linux
# or powershell.exe for Windows
command: zsh

# Specify the current working directory path
# the default is the current working directory path
cwd: /Users/user/Projects/easyborg

# Export additional ENV variables
env:
  recording: true

# Explicitly set the number of columns
# or use `auto` to take the current
# number of columns of your shell
cols: 100

# Explicitly set the number of rows
# or use `auto` to take the current
# number of rows of your shell
rows: 20

# Amount of times to repeat GIF
# If value is -1, play once
# If value is 0, loop indefinitely
# If value is a positive number, loop n times
repeat: 0

# Quality
# 1 - 100
quality: 1

# Delay between frames in ms
# If the value is `auto` use the actual recording delays
frameDelay: auto

# Maximum delay between frames in ms
# Ignored if the `frameDelay` isn't set to `auto`
# Set to `auto` to prevent limiting the max idle time
maxIdleTime: 500

# The surrounding frame box
# The `type` can be null, window, floating, or solid`
# To hide the title use the value null
# Don't forget to add a backgroundColor style with a null as type
frameBox:
  type: solid
  title: null
  style: []

# Add a watermark image to the rendered gif
# You need to specify an absolute path for
# the image on your machine or a URL, and you can also
# add your own CSS styles
watermark:
  imagePath: null
  style: []

# Cursor style can be one of
# `block`, `underline`, or `bar`
cursorStyle: block

# Font family
# You can use any font that is installed on your machine
# in CSS-like syntax
fontFamily: "Monaco, Lucida Console, Ubuntu Mono, Monospace"

# The size of the font
fontSize: 12

# The height of lines
lineHeight: 1

# The spacing between letters
letterSpacing: 0

# Theme
theme:
  background: "#15191e"
  foreground: "#dbdbdb"
  cursor: "#fefefe"
  black: "#14181d"
  red: "#fc4384"
  green: "#b3e33b"
  yellow: "#c6c43f"
  blue: "#2d42c0"
  magenta: "#b148b8"
  cyan: "#58c2c5"
  white: "#c7c7c7"
  brightBlack: "#676767"
  brightRed: "#cf7e77"
  brightGreen: "#81e397"
  brightYellow: "#eae14a"
  brightBlue: "#a7aaec"
  brightMagenta: "#d382db"
  brightCyan: "#8ef9fd"
  brightWhite: "#fefefe"