# -----------------------------------------------------------------------------
# Global
# -----------------------------------------------------------------------------

paths = [
    "~/Documents",
    "~/Pictures"
]

# -----------------------------------------------------------------------------
# Repositories
# -----------------------------------------------------------------------------

[repositories.HDB]
type = "backup"
path = "/path/to/local/backup"

[repositories.SRVB]
type = "backup"
path = "ssh://user@example.com:/backup/location"

[repositories.HDA]
type = "archive"
path = "/path/to/local/archive"

[repositories.SRVA]
type = "archive"
path = "ssh://user@example.com:/archive/location"
